import React from 'react';
import { 
  Box, 
  Container, 
  Heading,
  HStack, 
  SimpleGrid, 
  Text, 
  Image, 
  VStack,
  Divider,
  useBreakpointValue 
} from '@chakra-ui/react';
import { keyframes } from '@emotion/react';
import { motion } from 'framer-motion';
import CoinsmallR from '../images/coinsmallR.webp';
import EthLogo from '../images/eth.svg';
import BaseLogo from '../images/base.svg';
import BscLogo from '../images/bnb.svg';
import SolLogo from '../images/solana.svg';

const MotionBox = motion.create(Box);

const gradientAnimation = keyframes`
  0% { background-position: 0% 50%; }
  50% { background-position: 100% 50%; }
  100% { background-position: 0% 50%; }
`;

const baseCardStyle = {
  fontFamily: "Slackey, cursive",
  fontSize: "18px",
  color: "#FFFFFF",
  textShadow: "1px 1px #2A3335",
  rounded: "md",
  p: 1,
  w: "100%",
  backgroundSize: '200% 200%',
  animation: `${gradientAnimation} 1s ease infinite`
};

const TokenInfoSection = () => {
  const numberFontSize = useBreakpointValue({ base: '16px', md: '20px' });
  const textFontSize = useBreakpointValue({ base: '16px', md: '20px' });
  
  const topContentHeight = "80px"; 

  return (
    <Box as="section" py={20} textAlign="center" id="tokenomics">
      <Container maxW="container.lg" >
        <Heading
          as="h2"
          fontFamily="Slackey, cursive"
          fontWeight="bold"
          fontSize="28px"
          textTransform="uppercase"
          color="#FFFFFF"
          textShadow="2px 2px #2A3335"
          mb={8}
        >
          Tokenomics & Revenue Sharing
        </Heading>

        <Text textAlign="left" fontSize={{ base: "16px", md: "18px" }} mb={8} color="white">
          Bet Mianus is a revolutionary crypto gambling platform where every wager not only delivers exhilarating gameplay but also rewards our community. Profits generated by the platform are funneled directly back to those who stake the $Mianus token, ensuring that our users share in every win.
        </Text>

        <SimpleGrid columns={{ base: 1, md: 3 }} spacing={8}>
          <MotionBox 
            {...baseCardStyle} 
            bgGradient="linear(to-r, #FF6F91, #FFBC42)" 
          >
            <VStack spacing={2} h="100%">
              <Box 
                h={topContentHeight} 
                w="100%" 
                display="flex" 
                alignItems="center" 
                justifyContent="center"
              >
                <VStack spacing={1}>
                  <Text fontFamily="'Slackey', sans-serif" fontSize={numberFontSize} color="white">
                    100,000,000,000
                  </Text>
                  <Text fontFamily="'Slackey', sans-serif" fontSize={numberFontSize} color="white">
                    One Hundred Billion Mianus
                  </Text>
                </VStack>
              </Box>
              <Divider borderColor="white" />
              <Text fontFamily="'Slackey', sans-serif" fontSize={textFontSize} color="white" pt={2}>
                Mianus Total Supply
              </Text>
            </VStack>
          </MotionBox>


          <MotionBox 
            {...baseCardStyle}
            bgGradient="linear(to-r, #42FFA1, #6FFFD2)" 
          >
            <VStack spacing={2} h="100%">
              <Box 
                h={topContentHeight} 
                w="100%" 
                display="flex" 
                alignItems="center" 
                justifyContent="center"
              >
                <Image src={CoinsmallR} alt="Mianus Coin Logo" boxSize="50px" />
              </Box>
              <Divider borderColor="white" />

              <Text fontFamily="'Slackey', sans-serif" fontSize={textFontSize} color="white" pt={2}>
                Mianus Logo
              </Text>
            </VStack>
          </MotionBox>

          <MotionBox 
            {...baseCardStyle}
            bgGradient="linear(to-r, #42A1FF, #6FD2FF)" 
          >
            <VStack spacing={2} h="100%">

              <Box 
                h={topContentHeight} 
                w="100%" 
                display="flex" 
                alignItems="center" 
                justifyContent="center"
              >
                <HStack spacing={4}>
                  <Image src={EthLogo} alt="Ethereum" boxSize="40px" />
                  <Image src={BaseLogo} alt="Base" boxSize="40px" />
                  <Image src={BscLogo} alt="BSC" boxSize="40px" />
                  <Image src={SolLogo} alt="Solana" boxSize="40px" />
                </HStack>
              </Box>
              <Divider borderColor="white" />
              <Text fontFamily="'Slackey', sans-serif" fontSize={textFontSize} color="white" pt={2}>
                Mianus Chains
              </Text>
            </VStack>
          </MotionBox>
        </SimpleGrid>

        <Text 
          textAlign="left" 
          fontSize={{ base: "16px", md: "18px" }}  
          mt={8} 
          color="white"
        >
          With the crypto gambling market booming, we’re set to become a major player in the industry. Moreover, leveraging innovative wormhole NTT smart contracts, the $Mianus token is natively multichain, offering seamless, cross-chain transactions and empowering you to engage with digital finance like never before.
        </Text>
      </Container>
    </Box>
  );
};

export default TokenInfoSection;
